# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b559eebb4361d4278832ffa5df7e7968fb7ada873903c32f87e66f7f472174e28116bb52bb2781d4cb0656e67cf5451c7801ada83459db1ee0d3b65b5f4b56e4

test:
  secret_key_base: 91dc2c314baccd3c0026d45a0984e91f5131a94ca85b6ef8ce4e255ce629384ba8535ba8dfbb434beab141a09f92b831777df6028d30fac922e8b6410af994b0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: 5bb37e679ad7136277a7cca3420f5ef9b7913bdfd2b55550fb57cddb7edd07506deb6c14b251141fca793405522aefb74f348665f7c3e7a0394b0bb0bd2cb7e9
