class CreatePackets < ActiveRecord::Migration[5.1]
  def change
    create_table :packets do |t|
      t.integer :user_id
      t.integer :packet_number
      t.integer :vendor_number
      t.date :requested_date
      t.date :due_date
      t.boolean :completed
      t.string :company_name
      t.string :company_type
      t.string :dba
      t.string :address_1
      t.string :address_2
      t.string :city
      t.string :zip
      t.string :state
      t.string :cntry_code
      t.string :ship_address_1
      t.string :ship_address_2
      t.string :ship_city
      t.string :ship_zip
      t.string :ship_state
      t.string :cntry_code
      t.string :primary_contact
      t.string :phone_1
      t.string :phone_2
      t.string :email
      t.string :fax
      t.string :website
      t.string :qa_name
      t.string :qa_phone_1
      t.string :qa_phone_1_ext
      t.string :qa_phone_2
      t.string :qa_email
      t.string :ops_name
      t.string :ops_phone_1
      t.string :ops_phone_1_ext
      t.string :ops_phone_2
      t.string :ops_email
      t.text :notes
      t.string :usda_establishment_name_1
      t.string :usda_establishment_number_1
      t.text :mock_recall_sop_1
      t.date :mock_recall_date_1
      t.boolean :recall_this_year_1
      t.string :recall_1
      t.string :bone_foreign_1
      t.string :complaint_1
      t.string :problems_1
      t.string :haccp_1_certificate
      t.string :haccp_1_type
      t.string :haccp_1_company
      t.integer :haccp_1_score
      t.date :haccp_1_expires
      t.date :haccp_1_scheduled
      t.string :usda_establishment_name_2
      t.string :usda_establishment_number_2
      t.text :mock_recall_sop_2
      t.date :mock_recall_date_2
      t.boolean :recall_this_year_2
      t.string :recall_2
      t.text :bone_foreign_2
      t.text :complaint_2
      t.text :problems_2
      t.string :haccp_2_certificate
      t.string :haccp_2_type
      t.string :haccp_2_company
      t.integer :haccp_2_score
      t.date :haccp_2_expires
      t.date :haccp_2_scheduled
      t.string :usda_establishment_name_3
      t.string :usda_establishment_number_3
      t.text :mock_recall_sop_3
      t.date :mock_recall_date_3
      t.boolean :recall_this_year_3
      t.string :recall_3
      t.text :bone_foreign_3
      t.text :complaint_3
      t.text :problems_3
      t.string :haccp_3_certificate
      t.string :haccp_3_type
      t.string :haccp_3_company
      t.integer :haccp_3_score
      t.date :haccp_3_expires
      t.date :haccp_3_scheduled
      t.string :non_disclosure
      t.string :w9
      t.string :guarantee
      t.string :liability
      t.string :additional_string_1
      t.string :additional_string_2
      t.string :additional_string_3
      t.string :additional_string_4
      t.string :additional_string_5
      t.integer :additional_integer_1
      t.integer :additional_integer_2
      t.integer :additional_integer_3
      t.integer :additional_integer_4
      t.integer :additional_integer_5

      t.timestamps
    end
  end
end
