class CreateProducts < ActiveRecord::Migration[5.1]
  def change
    create_table :products do |t|
      t.integer :packet_id
      t.string :species
      t.string :breed
      t.string :product_name
      t.string :product_code
      t.string :vendor_code
      t.string :vendor_name
      t.boolean :case_piece
      t.string :box
      t.string :box_type
      t.text :box_details
      t.string :box_units
      t.float :box_length
      t.float :box_width
      t.float :box_height
      t.integer :box_count
      t.boolean :piece_box
      t.string :piece_pack
      t.integer :piece_count
      t.string :package_photo
      t.string :label
      t.string :label_type
      t.string :label_details
      t.string :label
      t.string :safe
      t.string :weight_units
      t.float :weight_max
      t.float :weight_target
      t.float :weight_min
      t.string :product_photo
      t.string :bug
      t.string :production_date
      t.integer :pallet_layers
      t.integer :pallet_count_per_layer
      t.float :pallet_length
      t.float :pallet_width
      t.float :pallet_height
      t.boolean :never
      t.string :never_doc
      t.boolean :withdrawal
      t.string :withdrawal_doc
      t.numeric :withdrawal_days
      t.boolean :gmo_free
      t.string :gmo_free_doc
      t.boolean :organic
      t.string :organic_doc
      t.boolean :vaccinated
      t.string :vaccinated_doc
      t.integer :vaccinated_age
      t.boolean :humane
      t.string :humane_doc
      t.boolean :traceable
      t.string :traceable_doc
      t.integer :sqft_inside
      t.integer :sqft_outside
      t.integer :sqft_total
      t.string :sqft_doc
      t.boolean :pastured
      t.string :pastured_doc
      t.boolean :omega3
      t.string :omega3_doc
      t.boolean :vegetable
      t.string :vegetable_doc
      t.string :other_claims
      t.string :other_doc
      t.integer :prod_to_receipt
      t.integer :shelf_life
      t.text :production_changes
      t.numeric :storage_temp
      t.string :microbe
      t.string :physical
      t.string :vendor_spec
      t.string :usda_approve
      t.string :allergens
      t.string :additional_string_1
      t.string :additional_string_2
      t.string :additional_string_3
      t.string :additional_string_4
      t.string :additional_string_5
      t.integer :additional_integer_1
      t.integer :additional_integer_2
      t.integer :additional_integer_3
      t.integer :additional_integer_4
      t.integer :additional_integer_5

      t.timestamps
    end
  end
end
